import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { isThereServerSession } from "@/hooks/session";
import NavBar from "../components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { session } = await isThereServerSession();
  console.log(session);
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <NavBar />
        </nav>
        {children}
      </body>
    </html>
  );
}
