import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";

import "./globals.css";
import QueryProvider from "./provider";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <QueryProvider>
      <html lang="en">
        <body
          className={cn(
            "min-h-screen bg-background font-sans antialiased",
            fontSans.variable,
            "flex",
            "flex-col"
          )}
        >
          <div className="w-[1500px] mx-auto">
            <nav>
              <Link href="/" className="m-2">
                Home
              </Link>
              <NavBar />
              <Link href="/community" className="m-2">
                커뮤니티
              </Link>
              <Link href="/mypage" className="m-2">
                마이페이지
              </Link>
            </nav>
            {children}
          </div>
        </body>
      </html>
    </QueryProvider>
  );
}
