import { Metadata } from "next";
import { PropsWithChildren } from "react";

export const metadata: Metadata = {
  title: "건강기능식품 전체 목록",
  description: "Generated by create next app",
};

const layout = ({ children }: PropsWithChildren) => {
  return (
    <>
      <div>{children}</div>
    </>
  );
};

export default layout;
